src/components/Form/Checkbox.js
src/components/Form/docs.md

Add disabled property to checkbox

---

src/components/Typography/docs.md
src/components/Typography/styles.js

SerifBold{36,17}
SansSerifMedium{16}

Add font styles needed for profile page

---

package-lock.json
package.json
src/components/CommentComposer/CommentComposer.js

Also auto-focus the textarea when the component is mounted.

feat: use react-textarea-autosize to automatically expand CommentComposer

---

src/components/CommentComposer/CommentComposer.js
src/components/CommentComposer/CommentComposerError.js
src/components/CommentComposer/docs.md
src/components/CommentComposer/index.js
src/index.js

This extends the `CommentComposer` component with ability to show errors.

Comment composer error

---

src/components/Overlay/Overlay.js
src/components/Overlay/OverlayToolbar.js
src/components/Overlay/docs.imports.js
src/components/Overlay/docs.md
src/components/Overlay/index.js
src/index.js
src/lib.js
src/theme/zIndex.docs.md
src/theme/zIndex.js

feat: Overlay, OverlayToolbar

---

src/components/Comment/Comment.js
src/components/Comment/CommentHeader.js
src/components/Comment/docs.md
src/components/CommentTree/DepthBar.js
src/components/CommentTree/LoadMore.js
src/components/CommentTree/Node.js
src/components/CommentTree/Row.js
src/components/CommentTree/docs.imports.js
src/components/CommentTree/docs.md

Looking at the diff the changes aren't that big, but it felt much more complicated while I was doing them. Unfortunately there were breaking changes in the API, in the `LoadMore` component. See the corresponding section in the catalog for different renderings of the component.
I won't attach a screenshot of the catalog page, go have a look at the preview deployment once it's ready.

Comment node redesign

---

src/components/Center/docs.md
src/components/Center/index.js
src/components/Figure/Image.js
src/components/Figure/docs.md
src/components/Figure/index.js
src/components/InfoBox/InfoBox.js
src/components/InfoBox/docs.md
src/components/Overlay/docs.md
src/components/PullQuote/PullQuote.js
src/components/PullQuote/docs.md
src/components/Social/Tweet.js
src/components/TeaserFeed/docs.md
src/components/TeaserFront/AuthorLink.js
src/components/TitleBlock/docs.md
src/components/Typography/Editorial.js
src/components/Typography/Interaction.js
src/components/Typography/docs.md
src/index.js
src/lib.js
src/templates/Editorial/index.js

Changes
- mv `Editorial.AuthorLink` to `Editorial.A`
- add `Editorial.Emphasis` aka bold
- rm regular breakout size (just use undefined)
- unify figure exports
And some clean up and doc fixes.

Link, Emphasis, Refactor & Clean Up

---

src/components/Social/Tweet.js
src/components/Video/Meta.js
src/components/Video/Video.js
src/components/Video/docs.md
src/components/Video/index.js
src/index.js
src/lib.js
src/templates/Article/docs.md
src/templates/Article/index.js

Preview:
https://r-styleguide-pr-53.herokuapp.com/video
https://r-styleguide-pr-53.herokuapp.com/templates/article#video
Related pull requests:
https://github.com/orbiting/publikator-backend/pull/18
https://github.com/orbiting/publikator-frontend/pull/81

feat: Video embed

---

src/components/Video/Video.js
src/components/VideoPlayer/Player.js
src/templates/Article/docs.md
src/templates/Article/index.js

Preview: https://r-styleguide-pr-60.herokuapp.com/templates/article#video-player
Also updates the video embed thumbnail to match the video player (play icon size and darkened thumbnail).

feat: VideoPlayer (for owned videos) in article template

---

src/templates/Article/index.js

Changelog:
- passes the !loose as compact option to the list component

feat: add compact option for lists

---

src/templates/Front/index.js

Changelog:
- TileTeaser can have no image. Editor options adjusted accordingly

feat: New option to hide image in tile teasers

---

src/components/Figure/Caption.js
src/templates/Article/index.js
src/templates/Front/index.js

Figuregroups in Article Template

feat: add min width to figure caption and clean up template section

---

src/components/Figure/Caption.js
src/templates/Article/index.js

Figurecaption module instead of paragraph module

Figuregroup

---

src/components/TeaserFeed/index.js
src/templates/EditorialNewsletter/email/Center.js
src/templates/EditorialNewsletter/email/Container.js
src/templates/EditorialNewsletter/email/Header.js
src/templates/EditorialNewsletter/schema.js

fix(EditorialNewsletter): Add link to web version in email header and footer

---

src/templates/Article/index.js

Changelog:
- Add new fields to meta rule in article template, that will get connected to a repo search component in the publikator

feat: 3 new custom fields that should get rendered as repo search fields

---

src/components/Typography/Editorial.js
src/components/Typography/docs.md

https://r-styleguide-pr-98.herokuapp.com/typography#note

feat: Editorial (foot)note

---

src/components/Typography/Editorial.js
src/components/Typography/Interaction.js
src/components/Typography/docs.md
src/components/Typography/index.js
src/components/Typography/styles.js
src/lib.js
src/templates/Article/docs.md
src/templates/Article/index.js
src/templates/EditorialNewsletter/docs.md
src/templates/EditorialNewsletter/email/Center.js
src/templates/EditorialNewsletter/email/HR.js
src/templates/EditorialNewsletter/email/Paragraph.js
src/templates/EditorialNewsletter/schema.js
src/theme/fonts.js

Add cursive and horizontal rule.
and activate `Editorial.Note` in mdast.

Typogrrrrr

---

src/components/AudioPlayer/Player.js

https://r-styleguide-pr-101.herokuapp.com/audioplayer

fix(AudioPlayer): Remove mute button and hide "0:00" before playing

---

src/components/AudioPlayer/Player.js

fix(AudioPlayer): no spinner in iOS before playing starts

---

src/components/Chart/Lines.js
src/components/Chart/Lines.layout.js
src/components/Chart/index.js
src/components/Typography/styles.js
src/templates/Article/index.js

_censored title and source, cause we're public here^^_

Charts Polish

---

src/templates/Front/docs.md
src/templates/Front/index.js

https://r-styleguide-pr-112.herokuapp.com/templates/front

fix(TeaserFrontTile): enable "onlyImage" editor option and fix front template doc

---

src/components/Chart/Bars.docs.md
src/components/Chart/Bars.js
src/components/Chart/Lines.layout.js
src/components/Chart/Lollipops.docs.md
src/components/Chart/TimeBars.docs.md
src/components/Chart/TimeBars.js
src/components/Chart/index.js
src/components/Chart/utils.js
src/index.js
src/templates/Article/docs.md
src/templates/Article/index.js

Last mayor base charts from my side for now.

feat(Charts): port time bars

---

src/components/Video/Video.js

Use youtube-nocookie embed

---

src/components/TeaserFront/Image.js
src/components/TeaserFront/Image.md
src/components/TeaserFront/Text.js

Fixes https://github.com/orbiting/styleguide/issues/139

fix(FrontImage): hide overflow both for unpositioned (mobile) and positioned (desktop) layout

---

src/components/Form/Radio.js
src/components/Form/docs.md

feat(Radio): add disabled property

---

src/templates/Article/index.js

Related to: https://github.com/orbiting/publikator-frontend/pull/155

feat(schema): new logbook entry added to article schema

---

src/templates/Article/index.js

feat(schema): add global inlines to headlines and infobox title

---

src/components/VideoPlayer/Player.js

conveniences - a nice word for: fixes
only the VideoPlayer who has the focus toggles

VideoPlayer convenience

---

src/components/TeaserFront/Format.js
src/templates/Front/index.js

Only mix colors for frontImage teasers, otherwise directly use feuilleton color.

fix(Front): now really fix feuilleton format color

---

src/components/Form/Autocomplete.js

fix(components/Form/Autocomplete): show a focused label if !!value

---

src/components/Form/FieldSet.js
src/components/Form/docs.md

feat(FieldSet): explanation after field

---

src/components/Figure/index.js
src/templates/Article/index.js

feat(FigureCover): add breakout size

---

src/components/TeaserFront/Tile.js
src/components/TeaserFront/Tile.md

Related to https://github.com/orbiting/republik-frontend/pull/220

fix(FrontTileRow): support reverse direction on mobile

---

src/templates/Article/index.js

fix(Article): strong or emphasis in link regression

---

src/components/Dossier/TileHeadline.js
src/components/Typography/styles.js
src/templates/Article/docs.md
src/templates/Article/teasers.js
src/templates/Front/index.js

feat(dossier): support scribble

---

src/templates/Article/teasers.js

Fixes https://github.com/orbiting/publikator-frontend/issues/182

fix(articleCollection): link format to format URL

---

src/components/PullQuote/Text.js
src/components/Typography/docs.md
src/components/Typography/styles.js

Needed for https://github.com/orbiting/republik-frontend/pull/228

feat(PullQuoteText): add 'large' size for marketing use

---

src/components/TeaserFeed/docs.md
src/components/TeaserFeed/index.js
src/index.js

feat(TeaserFeed): add optional bar

---

src/components/TeaserFeed/Container.js
src/components/TeaserFeed/InternalOnlyTag.js
src/components/TeaserFeed/docs.md
src/components/TeaserFeed/index.js
src/index.js
src/lib/translations.json

Required for https://github.com/orbiting/republik-frontend/pull/257

feat(TeaserFeed): add subtle tag for prepublished documents

---

src/components/List/List.js
src/components/List/docs.md

Fixes https://github.com/orbiting/styleguide/issues/221
Preview: https://r-styleguide-pr-222.herokuapp.com/list

fix(List): indent on desktop, just like mobile

---

src/components/Chart/Bars.js
src/components/Chart/ScatterPlots.docs.md
src/components/Chart/ScatterPlots.js
src/components/TeaserFront/CreditLink.js

- inline labels
- customize details in hover tooltip

More Labels for ScatterPlots

---

src/components/Button/index.js
src/components/Chart/Bars.js
src/components/CommentTeaser/CommentTeaser.js
src/components/CommentTeaser/docs.md
src/components/Discussion/Composer/CommentComposerPlaceholder.js
src/components/Discussion/Composer/docs.imports.js
src/components/Discussion/Internal/Comment/Body.js
src/components/Discussion/Internal/Comment/Header.js
src/components/Discussion/Internal/Comment/render.js
src/components/Discussion/Internal/Composer/Actions.js
src/components/Discussion/Internal/docs.md
src/components/Discussion/Tree/CommentList.js
src/components/Discussion/Tree/LoadMore.js
src/components/Discussion/Tree/docs.md
src/components/Discussion/__docs__/comments.js
src/components/Discussion/index.js
src/components/Dossier/More.js
src/components/Figure/index.js
src/components/Gallery/NavOverlay.js
src/components/Overlay/Overlay.js
src/components/Overlay/docs.md
src/components/Social/Header.js
src/components/TeaserFront/CreditLink.js
src/components/Typography/Editorial.js
src/components/Typography/styles.js
src/components/Video/Meta.js
src/lib.js
src/lib/slug.js
src/lib/useBoundingClientRect.js

- introduce `@meda(hover)`
- fix discussion eslint warnings and suppress hydration warning for timestamps
- fix overlay scroll
- expose `renderCommentMdast` for https://github.com/orbiting/crowd-questions

Discussion v4 Fixes

---

src/components/InfoBox/InfoBox.js
src/components/InfoBox/ListItem.js
src/components/InfoBox/Subhead.js
src/components/InfoBox/docs.md
src/components/InfoBox/index.js
src/components/List/List.js
src/components/Typography/docs.md
src/components/Typography/styles.js
src/lib.js
src/templates/Article/docs.md
src/templates/Article/index.js
src/templates/Article/teasers.js

Implementation of https://github.com/orbiting/styleguide/issues/225
Docs preview:
https://r-styleguide-pr-242.herokuapp.com/infobox#ltinfoboxsubhead-gt-and-ltinfoboxlistitem-gt
https://r-styleguide-pr-242.herokuapp.com/templates/article#with-list

feat(Article): lists in infoboxes

---

src/components/Center/docs.md
src/components/Center/index.js
src/components/Figure/index.js
src/templates/Article/index.js
src/templates/Article/utils.js

- für nen Glossar via Bettina
- für Diashows via Brigitte

#zwischentitel & map size of figure group

---

src/catalogTheme.css
src/components/Chart/Maps.docs.md
src/components/Chart/Maps.js
src/components/TeaserActiveDebates/DebateComment.js
src/components/TeaserActiveDebates/DebateHeader.js
src/components/TeaserCarousel/Carousel.js
src/components/TeaserCarousel/Row.js
src/components/TeaserCarousel/Tile.js
src/components/TeaserCarousel/constants.js
src/components/TeaserCarousel/docs.md
src/components/Typography/styles.js
src/index.js
src/templates/Front/docs.md

Front 2: Carousel Arrows, Sizes, Point Map Colors and Tweaks

---

src/components/Button/docs.md
src/components/Button/index.js
src/templates/Article/docs.md
src/templates/Article/index.js
src/templates/EditorialNewsletter/docs.md
src/templates/EditorialNewsletter/email/Button.js
src/templates/EditorialNewsletter/email/index.js
src/templates/EditorialNewsletter/schema.js
src/templates/EditorialNewsletter/web/Button.js
src/templates/EditorialNewsletter/web/index.js

_Still needs some testing_
- Extend button component to allow using it with links
- Setup mdast schema to parse a markdown buttonlink and match it to the button component (available for article and newsletter)
- Create a table-based button component to use in the email rendering of the markdown

Mdast button

---

.github/workflows/push.yml
src/components/Chart/Hemicycle.js
src/templates/Article/index.js
src/templates/Dossier/index.js
src/templates/Format/index.js
src/templates/Section/index.js

Add `paynotes` variable to templates. We use this variable to decide whether we should render the custom paynotes form in publikator

Custom paynotes

---

src/components/TeaserCarousel/Carousel.js
src/components/TeaserCarousel/Grid.js
src/components/TeaserCarousel/Row.js
src/components/TeaserCarousel/Tile.js
src/components/TeaserCarousel/TileContainer.js
src/components/TeaserCarousel/constants.js
src/components/TeaserCarousel/docs.md
src/components/TeaserCarousel/index.js
src/templates/Article/teasers.js
src/templates/Front/index.js

feat(TeaserCarousel): grid mode

---

src/templates/EditorialNewsletter/email/index.js
src/templates/EditorialNewsletter/schema.js
src/templates/EditorialNewsletter/web/index.js

Use regular List component on web rendering

Newsletter

---

src/components/Callout/CalloutMenu.js
src/components/Callout/docs.md
src/components/Callout/index.js
src/components/Discussion/Internal/Comment/Header.js
src/components/TeaserFeed/Container.js
src/components/TeaserFeed/index.js
src/index.js
src/theme/zIndex.js

- minor styling amends to the callout
- add `open` property to callout menu (used for ?mute=1 links in frontend)

Notifications fixes

---

src/templates/EditorialNewsletter/email/Center.js
src/templates/EditorialNewsletter/email/Header.js

fix(EditorialNewsletter): Revert to covid-19 trial post scriptum

---

src/components/AudioPlayer/Player.js

fix(audioplayer): loader position and client side Link

---

package-lock.json
package.json
src/components/Overlay/Overlay.js
src/lib/useBodyScrollLock.js

Reworked body lock hook to support new header which is transitioning between two locked popovers.

Fix multi body lock

---

src/components/Callout/CalloutMenu.js
src/components/Callout/docs.md
src/components/TeaserShared/SectionTitle.js

Switches to the left of icon when align="right" is provided

Adds optional label to callout button

---

src/components/Callout/CalloutMenu.js
src/components/Callout/docs.md

fix(CalloutMenu): fix menu position

---

src/components/LazyLoad/index.js
src/components/TeaserActiveDebates/ActiveDebates.js
src/components/TeaserFeed/Credit.js
src/components/TeaserFeed/index.js
src/components/TeaserMyMagazine/TeaserMyMagazine.js
src/components/TeaserMyMagazine/__docs__/index.js
src/components/TeaserMyMagazine/__docs__/myMagazineExamples.js
src/components/TeaserMyMagazine/docs.md
src/components/TeaserMyMagazine/index.js
src/components/TeaserShared/SectionTitle.js
src/index.js
src/templates/Front/liveTeasers.js

Meine Republik Teaser

---

src/components/TeaserMyMagazine/TeaserMyMagazine.js
src/components/TeaserMyMagazine/__docs__/myMagazineExamples.js
src/components/TeaserMyMagazine/docs.md

- Schriftgrösse
- Titel statt ShortTitle
- Titelformat: "Format: Titel"

Anpassung Style Meine Republik

---

src/templates/Page/docs.md
src/templates/Page/index.js

Decided this was a dumb idea after all.

fix(Page): delete unused excludeFromFeed editor option

---

src/components/TeaserMyMagazine/TeaserMyMagazine.js
src/components/TeaserMyMagazine/__docs__/myMagazineExamples.js
src/components/TeaserMyMagazine/docs.md
src/templates/Front/liveTeasers.js

- Schriftarten Titel angepasst
- Grauer Rahmen
- Layout angepasst, einheitlich mit dialog

style(TeaserMyMagazie): design tweaks teasermymagazine

---

src/components/Collapsable/Collapsable.js
src/components/CommentTeaser/CommentTeaser.js
src/components/Discussion/Internal/Comment/IconLink.js
src/components/Discussion/Tree/CommentList.js
src/components/Form/Field.js
src/components/InfoBox/InfoBox.js
src/components/InfoBox/docs.md
src/components/Typography/Interaction.js

feat(Infobox): scroll to top when closing

---

src/theme/colors.js

style(colors): fix fro gradient overlay with bodara tweak

---

src/lib/inQuotes.docs.md
src/lib/inQuotes.js
src/lib/translations.json

In quotes fix

---

src/lib/inQuotes.js

fix(inQuotes): fix replaceAll not supported in FF

---

package.json
src/components/CommentTeaser/CommentTeaser.js
src/components/Discussion/Internal/Comment/Actions.js
src/components/Discussion/Internal/Comment/Body.js
src/components/Discussion/Internal/Comment/Header.js
src/components/Discussion/Internal/docs.md
src/lib/translations.json

Replaces https://github.com/orbiting/styleguide/pull/355 due to squashing instead of rebasing merge

Discussion: Hide unpublished nodes (2nd merge attempt)

---

src/components/IconButton/docs.md
src/components/IconButton/index.js

Useful for publicator's week nav.

feat(IconButton): allow to specify a different icon size

---

src/components/TeaserFeed/Container.js
src/components/TeaserFeed/docs.md
src/components/TeaserFeed/index.js
src/components/TeaserFeed/utils.js
src/templates/Article/docs.md
src/templates/Article/index.js
src/templates/docs.js

feat(TeaserFeed): add series title to feed

---

src/catalogTheme.css
src/catalogTheme.js
src/index.js

Darkmode swithc for the styleguide.
Not included:
- responsive view: the iframe makes dark mode switch buggy
- adaptation of individual doc pages: this will be done on a case-by-case basis

Darkmode switch

---

src/components/Center/index.js
src/components/TitleBlock/index.js

For styling purposes with dynamic components

feat(CenterAndTitleBlock): add classname

---

src/components/Chart/Maps.docs.md
src/components/Chart/Maps.js

Two fixes
- tooltip position when color legend is in page flow
- only render hover point border when a tooltip is available

Improve Static Point Maps

---

src/components/Chart/Bars.js

fix(Barchart): pass empty string to lablegauger if no string

---

src/components/ShareImage/ShareImagePreview.js

1. Background image XOR format image gets rendered

Fixes for Sharetafel

---

src/components/Icons/docs.md
src/components/Icons/index.js
src/icons.js
src/index.js

feat(Icons): adds OpenSourceIcon

---

src/components/Overlay/OverlayToolbar.js
src/components/Overlay/docs.imports.js
src/components/Overlay/docs.md
src/components/Overlay/index.js
src/lib.js

Make OverlayToolbarClose consistent with our actual layout and conventions

fix(OverlayToolbar): align close icon right

---

src/components/CommentTeaser/CommentTeaser.js

- Add link around image of Comment Teaser

Add link to image comment teaser

---

src/components/Discussion/Composer/CommentComposer.js
src/components/Discussion/Tree/CommentList.js

- preselect tag in composer
- hide tag in comment list

Elections 2021

---

rollup.config.js

This PR fixes an issue, that caused an "Unexpected token"-error in {.ts,.tsx} files.

Fix build-setup to handle .ts(x) with babel

---

package-lock.json
package.json
src/components/Chart/Editor.docs.md
src/components/Chart/JSONEditor.js
src/components/Chart/Lines.js
src/index.js

Json Editor Experiment

---

src/components/SeriesNav/SeriesNavTile.js

fix(SeriesNavTile): add Paynote spacing
