orbiting/styleguide

- src/components/Typography/docs.md
- src/components/Typography/index.js
- src/components/Typography/styles.js
- src/index.js
- src/lib.js
Export all raw font styles and document in the catalog.
Font style is a combination of font cut, size, line height etc. By collecting the list I already noticed that we use a few slightly-different sizes, eg. `sansSerifMedium22` and `sansSerifRegular21`.
In the Sketch file I have I also saw some use of font with size 15. I didn't add that style yet, because then we'd have sizes 14, 15, and 16 – three sizes which are very close together.
If I plot the font sizes which are currently used, then they follow quite closely the Major Third scale (each size is 1.25 times larger than the next smaller size). We might want to make that more explicit in the future.
> feat: Export raw font styles

- package-lock.json
- package.json
One really nice feature of react v16 is that [components can return lists of elements](https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings), without the need to wrap the elements in a container (eg. a div). I'd like to make use of that feature in the Discussion components.
Note that this is potentially a breaking change:
BREAKING CHANGE: Since react is a peer dependency, you may have to upgrade react in your own
project.
> refactor: Upgrade react to 16

- src/components/CommentComposer/CommentComposer.js
- src/components/CommentComposer/CommentComposerHeader.js
- src/components/CommentComposer/docs.md
- src/components/CommentComposer/docs.t.js
- src/index.js
To show these components in the catalog I need a `t()` function. To make it convenient I created a a `docs.t.js` file in the component folder and expose that function to the whole catalog page using imports. But perhaps it would be better to store those strings in JSON files so that they can be used to seed the spreadsheet you have. And it would also allow us to show the required translation keys in the catalog pages.
> feat: CommentComposer component

- src/components/Comment/CommentHeader.js
- src/components/CommentTree/Collapse.js
- src/components/CommentTree/DepthBar.js
- src/components/CommentTree/LoadMore.js
- src/components/CommentTree/Node.js
- src/components/CommentTree/Row.js
- src/components/CommentTree/comments.js
- src/components/CommentTree/docs.imports.js
- src/components/CommentTree/docs.md
- src/components/CommentTree/index.js
- src/lib/translations.json
I had to change the structure of the CommentTree components because the tree-like structure didn't work well with the sections that decrease the indentation when they are expanded. Now it's more list-like, where each comment is shown in a separate row. That works well thanks to the React 16 feature where render functions can return lists of element that don't need to be wrapped in an anonymous container (usually a div).
This is technically a breaking change (since the `CommentTreeComponent` API has changed), but nobody was using that component yet.
> Comment tree refactor

- src/components/CommentComposer/docs.md
- src/components/CommentTree/Node.js
- src/components/CommentTree/Row.js
BREAKING CHANGE: The submitComment function must return a Promise which rejects with a string upon failure to submit a comment.
> feat: Show error in when submitComment fails inside a CommentTree

- src/components/CommentTeaser/CommentTeaser.js
- src/components/CommentTeaser/CommentTeaserFooter.js
- src/components/CommentTeaser/CommentTeaserHeader.js
- src/components/CommentTeaser/docs.imports.js
- src/components/CommentTeaser/docs.md
- src/components/CommentTeaser/index.js
- src/index.js
- src/lib.js
- src/lib/translations.json
FYI, we'll need the title/subtitle version for rendering "latestComments" on the profile page. And while I'm at it, I also added support for the displayAuthor header (to be used when highlighting specific user comments in editorial context).
> feat: CommentTeaser

- src/components/RawHtml/docs.md
- src/components/RawHtml/index.js
- src/index.js
- src/lib.js
Note that I've  removed most of the styles from the crowdfunding implementation, including the serif/sansSerif switch. I may add that back if we find a use case in publikator or republik frontends.
> feat: RawHtml

- src/components/CommentTree/Node.js
- src/components/CommentTree/Row.js
- src/components/CommentTree/docs.imports.js
This is required so that we can open the preference editor when the user clicks the edit icon in the CommentComposer component inside a tree.
> feat: pass onEditPreferences callback through CommentTreeNode to the CommentComposer

- src/components/Overlay/Overlay.js
- src/components/Overlay/OverlayBody.js
- src/components/Overlay/OverlayToolbar.js
- src/components/Overlay/docs.imports.js
- src/components/Overlay/docs.md
- src/components/Overlay/index.js
- src/lib.js
As discussed last week, make the overlay not full-viewport on larger devices. Overflow behavior can also be tested in the catalog.
> refactor: make overlay look nicer on large screens

- src/components/Comment/CommentActions.js
- src/components/Comment/docs.md
- src/components/CommentTree/Node.js
- src/components/CommentTree/Row.js
These changes are necessary to allow a discussion to be displayed if the user is not logged in. In that case hide all components which are used to submit new comments.
The logic is: if the CommentTree component receives a `displayAuthor`, the it assumes that the user can comment and makes all the composers available. If not then the *Antworten* button is hidden.
> Comment tree anonymous

- src/components/Comment/CommentHeader.js
- src/components/Comment/docs.md
- src/components/CommentComposer/CommentComposerHeader.js
- src/components/CommentTeaser/CommentTeaserHeader.js
- src/lib/styleMixins.js
I noticed that we have a few places where we use the three css declaration to ellipsize text (white-space, overflow, text-overflow) so I extracted them into an 'ellipsize' mixin.
Descenders in the CommentComposerHeaders were cut off due to combination of ellipsize and line-height: 1. See screenshot below.
And I refactored CommentHeader and CommentComposerHeader to make sure the ellipsis only shortens the name/description and leaves the timeago and verified check always visible. There's now an example of an overflowing CommentHeader in the catalog.
> Comment header overflow fix

- src/components/CommentTree/DepthBar.js
No change in functionality, just gets rid of a React warning.
> refactor: DepthBar: make head, tail optional

- src/components/CommentTree/Collapse.js
- src/components/CommentTree/LoadMore.js
- src/components/CommentTree/docs.md
⚠️  BREAKING CHANGE: The CommentTreeCollapse component now requires a visualDepth prop ⚠️
> refactor: CommentTreeCollapse: align the label with the visual depth

- src/components/CommentTree/Row.js
This makes it easier to tweak the magnitude of the visual depth of discussion rows.
The width of each bar depends on `profilePictureSize` and `profilePictureMargin` which are both defined in CommentHeader. You can tweak those numbers as needed. Here's an example of size=20 and margin=8:
> refactor: Use profilePicture{Size,Margin} for the negative left margin in Row

- src/components/Center/docs.md
- src/components/Center/index.js
- src/components/InfoBox/Figure.js
- src/components/InfoBox/InfoBox.js
- src/components/InfoBox/Text.js
- src/components/InfoBox/Title.js
- src/components/InfoBox/docs.md
- src/components/PullQuote/PullQuote.js
- src/components/PullQuote/docs.md
- src/index.js
- src/lib.js
Breakout defines all generic sizes, while PullQuote and InfoBox only support a limited set of sizes while enforcing some combinatory restrictions.
> feat: <Center /> and <Breakout />

- src/components/Figure/Caption.js
- src/components/Figure/Image.js
- src/components/Figure/docs.md
- src/components/Figure/index.js
- src/components/InfoBox/InfoBox.js
- src/components/InfoBox/docs.md
- src/components/PullQuote/docs.md
- src/components/Social/Tweet.js
- src/components/TeaserFeed/Format.js
- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Split.js
- src/components/TitleBlock/index.js
- src/components/Typography/Editorial.js
- src/components/Typography/docs.md
- src/index.js
- src/lib/styleMixins.js
- src/templates/Editorial/Container.js
- src/templates/Editorial/docs.md
- src/templates/Editorial/index.js
- src/templates/Meta/docs.md
- src/templates/Meta/index.js
- src/templates/docs.js
Notable Changes
- template creators
- add Meta template
- `FigureImage` props are now flat: `data={{src: '', alt: ''}}` becomes `src={''} alt={''}`
- add `center` size to `Figure` (essay template with figure in front of title, center wrap would be impractical here)
> Templates Round 2

- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Tile.js
- src/components/TeaserFront/Tile.md
- src/components/TeaserFront/Typo.js
- src/components/TeaserFront/Typo.md
- src/components/TeaserFront/TypoHeadline.js
- Makes `image` optional for tile teaser
- Supports a `small` version of `<TeaserFrontTypoHeadline.Interaction />`
- Adds social teaser examples for tile and typo teasers
- Plus an unrelated typographic adjustment for larger headlines in typo teasers.
Previews:
https://r-styleguide-pr-48.herokuapp.com/teaserfronttypo (very bottom)
https://r-styleguide-pr-48.herokuapp.com/teaserfronttile
> feat: Social variants of tile and typo front teasers.

- src/components/Social/Tweet.js
- src/components/Social/docs.md
Required for
https://github.com/orbiting/publikator-backend/pull/16
https://github.com/orbiting/publikator-frontend/pull/78
`playable` will not play the video/gif inline, but decorate the image with a play icon and link off to the tweet.
> fix(Tweet): Support playable media and "more" link

- src/components/List/List.js
- src/components/List/docs.md
- src/components/List/index.js
- src/components/Typography/Editorial.js
- src/components/Typography/styles.js
- src/index.js
- src/lib.js
- Preview: https://r-styleguide-pr-52.herokuapp.com/list
- Tested on IE
- Not using `list-style-type: 'somechar'` because it's not supported cross-browser
> feat: UL and OL

- src/components/Figure/Image.js
- src/components/Figure/docs.md
- src/components/Figure/index.js
For image URLs with sizing info.
While loading, the image itself is used as a placeholder with gray background and paddingBottom/height:0 sizing. When the image has loaded, we move back to the default image size at 100% width.
While image is loading:
Image has loaded:
> fix(Figure.Image): Reserve expected space while loading and support image resize

- package-lock.json
- package.json
- src/components/Center/index.js
- src/components/Figure/Image.js
- src/components/Figure/docs.md
- src/components/Figure/index.js
- src/components/Figure/utils.js
- src/components/Figure/utils.test.js
- src/components/InfoBox/InfoBox.js
- src/components/InfoBox/index.js
- src/components/PullQuote/PullQuote.js
- src/components/PullQuote/index.js
- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Image.md
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Split.md
- src/components/TitleBlock/index.js
- src/index.js
- src/templates/Article/docs.md
- src/templates/Article/index.js
- src/templates/Article/utils.js
- src/templates/Article/utils.test.js
- src/templates/docs.js
Add resize urls to article template (mdast context dependant) and front image and split (static sizes). Includes `srcSet` for retina and `maxWidth` handling to avoid displaying larger than source.
Also includes other fixes:
- fix breakout width after figure placeholder intro
- fix float left overflow
> FigureImage Resize

- package.json
See error:
```
~/work/publikator-backend [newsletter]$ yarn install
...
error @project-r/styleguide@5.23.0: The engine "node" is incompatible with this module. Expected version "8.4.0".
```
> fix: bump node version to be compatible with publikator-backend

- src/components/InfoBox/InfoBox.js
> fix: Clearfix for floating info box with image and short text

- src/components/Figure/utils.js
- src/components/Figure/utils.test.js
- src/templates/Article/index.js
> fix(Article): Don't set maxWidth on an edge-to-edge cover image.

- src/components/Typography/Interaction.js
To allow using e.g. <Interaction.H1> on the feed page greeting in republik-frontend. 
Sounds like overkill to create yet another headline style just for that page, plus they seem to large on crowdfunding mobile anyway:
> fix: Make interaction headlines responsive

- src/components/TeaserFront/Image.js
All front teasers are currently edge-to-edge, just the FrontImage may set maxWidth and screw up text positioning.
> fix(FrontImage): Shouldn't set maxWidth

- src/components/TeaserFeed/index.js
- src/components/Typography/index.js
- src/templates/EditorialNewsletter/email/SubSup.js
- src/templates/EditorialNewsletter/email/index.js
- src/templates/EditorialNewsletter/schema.js
- src/templates/EditorialNewsletter/web/index.js
Gmail Before:
Gmail After:
Don't get how https://github.com/orbiting/styleguide/pull/77/commits/4b3c6bae3a490087f50393df6b5077936e13c659 sneaked in here, I had already pushed that from a different branch in https://github.com/orbiting/styleguide/pull/76
> fix(EditorialNewsletter): sub/sup should have inline style for lineHeight:0

- src/components/Figure/Caption.js
- src/components/Figure/Image.js
- src/components/Figure/index.js
This was introduced by image placeholders (display: block), while unwrapped image's (display: inline) captions still have some default top spacing inherited from line-height. To reset spacing for both cases, we're also using `display: block` on normal images now and explicitly set the top margin on the caption.
Before:
After:
> fix(Figure): 5px top-margin for figure caption

- src/components/Center/index.js
- Aligns page content with footer and series top nav.
- Makes the mobile view slightly more compact.
- On article pages we might gain an extra word per line once in a while.
Before:
After:
> fix(Center): decrease mobile content padding from 20 to 15px

- src/templates/EditorialNewsletter/schema.js
Inserting images stopped working on the editorial newsletter template. With this change, things are working as intended again (tested end-to-end in mailchimp).
> fix(EditorialNewsletter): Re-activate button for inserting images

- src/templates/Article/docs.md
- src/templates/Article/index.js
- src/templates/Article/utils.js
- src/templates/Discussion/docs.md
- src/templates/Discussion/index.js
- src/templates/Dossier/docs.md
- src/templates/Dossier/index.js
- src/templates/EditorialNewsletter/docs.md
- src/templates/EditorialNewsletter/schema.js
- src/templates/Format/docs.md
- src/templates/Format/index.js
- src/templates/Front/docs.md
- src/templates/Front/index.js
This logic is currently in [publikator-backend/blob/master/lib/Document.js ](https://github.com/orbiting/publikator-backend/blob/master/lib/Document.js) but to display in publikator it makes more sense to colocate with the template, like repo prefix.
> feat(Templates): getPath on schema

- src/components/TeaserFront/Tile.js
- src/components/TeaserFront/Tile.md
- src/templates/Front/docs.md
- src/templates/Front/index.js
Allows to display a full-width or full-height image in a front tile.
Previews:
https://r-styleguide-pr-99.herokuapp.com/teaserfronttile#image-only
https://r-styleguide-pr-99.herokuapp.com/templates/front
In Publikator, all we'd need is an "imageOnly" checkbox for tiles.
Depends on https://github.com/orbiting/publikator-frontend/pull/131
> feat(FrontTile): add image-only use case, e.g. for cartoons

- src/templates/Article/index.js
Fixes the UI for Edge-To-Edge images in orbiting/publikator-frontend
> fix: use the centerFigure definiton in document rules

- src/components/VideoPlayer/Fullscreen.js
- src/components/VideoPlayer/Icons/Fullscreen.js
- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/fullscreen.js
Try out: https://r-styleguide-pr-105.herokuapp.com/videoplayer
- New fullscreen icon appears if browser supports fullscreen API
- In fullscreen mode, native controls are enabled
Chrome inline:
Chrome fullscreen:
Firefox fullscreen:
Safari fullscreen:
MS Edge fullscreen:
IE11 fullscreen:
iOS shows no fullscreen icon since API is not supported and it's playing fullscreen anyway.
> feat(VideoPlayer): add fullscreen mode

- src/components/Dossier/Teaser.md
- src/components/Dossier/TeaserIntro.js
- src/components/Figure/Byline.js
- src/components/Figure/Image.js
- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Image.md
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Split.md
- src/components/TeaserFront/Tile.js
- src/components/TeaserFront/Tile.md
- src/templates/Front/docs.md
- src/templates/Front/index.js
Approach:
- Re-use `<FigureByline>`
- Make sure it's inside a `position:relative` container
- Add a `position` attribute with a distinct set of positioning options
- No config options in Publikator needed other than entering the byline string
Previews:
https://r-styleguide-pr-107.herokuapp.com/teaserfrontimage
https://r-styleguide-pr-107.herokuapp.com/teaserfrontsplit
https://r-styleguide-pr-107.herokuapp.com/teaserfronttile
https://r-styleguide-pr-107.herokuapp.com/teaserfrontdossier
https://r-styleguide-pr-107.herokuapp.com/templates/front
Publikator PR: https://github.com/orbiting/publikator-frontend/pull/136
> feat: positioned byline for front teaser images

- src/components/AudioPlayer/Player.js
- src/components/AudioPlayer/docs.md
- src/index.js
- src/lib/translations.json
Instead of keeping the loading spinner around endlessly, provide a meaningful message and a link to retry.
> fix(AudioPlayer): more useful UX when source failed loading

- src/components/Chart/utils.js
Because [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) is not stable and implementation differs between Chrome and Safari we currently end up with incorrectly positioned labels SSR with v8 and then browser rendering with a different engine.
Example Safari
After Fix
I thought the react keys would catch it. But I do use index in many keys (not exclusively). Anyhow it's correct to stable sort anyhow since manual order in the dataset is supported by design.
> fix(Charts): stabilize sort and group by

- src/templates/Dossier/docs.md
mdast rendering is currently broken on
https://styleguide.republik.ch/templates/dossier
due to outdated markdown.
> fix: dossier template docs

- package-lock.json
- package.json
will bump republik-frontend directly on master
> fix: bump react-maskedinput (fixes broken input on Android Chrome)

- src/components/LazyLoad/Image.js
This only occurs for certain widths of the browser window and some specific images, but when it happens, it's ugly. Reason is a mismatch of the placeholder space (which is an exact padding-bottom percentage of the image's aspect ratio resulting in sub-pixel values), while the image size itself may get rounded to full pixels by the browser.
Before (note the red background shining through at the bottom):
After:
> fix(LazyLoad): prevent against the bottom line effect showing up on some front image teasers

- src/components/AudioPlayer/Player.js
Currently, on IE11 the AudioPlayer explodes when playback starts with this error message:
The error message suggests that IE11 has issues with Array.prototype.keys() at least in republik-frontend context -- which in fact is executed only when playing starts.
Currently I can't test this on IE11 locally, but I would like to check this speculative fix on .love.
TimeRanges interface: https://developer.mozilla.org/en-US/docs/Web/API/TimeRanges
> fix(AudioPlayer): resolve TimeRanges object without using keys()

- src/components/CommentBody/email/Paragraph.js
- src/components/Typography/Editorial.js
- src/components/Typography/Interaction.js
- src/templates/EditorialNewsletter/email/Paragraph.js
Seems like most browser were doing it, except for Chrome 🙃 
**before**
**after**
> fix(Typography): faux italic

- src/components/CommentBody/email/Blockquote.js
- src/components/CommentBody/email/index.js
- src/components/CommentBody/web/Blockquote.js
- src/components/CommentBody/web/index.js
- src/templates/Comment/docs.md
- src/templates/Comment/email.js
- src/templates/Comment/schema.js
- src/templates/Comment/web.js
Fixes https://github.com/orbiting/styleguide/issues/133
> fix(Comment): support non-paragraph content in blockquotes and nesting of blockquotes

- src/templates/Article/index.js
- src/templates/Article/teasers.js
text color links for article collections (requested by Christof)
fix empty data object being forwarded into center (reported by @wereHamster, thx!)
> Two Random Fixes

- src/components/TeaserFront/Text.js
Typical issue in production with longer leads:
With the fix, text may grow upwards:
> fix(frontimage): bottomleft/right positioning of text should be relative to bottom (instead of 50%)

- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/fullscreen.js
Right now we don't have a fullscreen button on iOS. But there's actually a way to request fullscreen on the video element directly on iOS.
> feat(VideoPlayer): enable fullscreen button on iOS

- src/templates/Article/docs.md
- src/templates/Article/dynamicComponent.js
- src/templates/Article/index.js
Support Edge-to-Edge dynamic components:
and raw mode without figure wrapping.
> feat(DynamicComponent): edge-to-edge and raw (without figure wrapper)

- src/templates/EditorialNewsletter/email/Cover.js
Outlook and some other clients show erros when a img src is missing:
In our current workflow all daily and soon weekly newsletters are sent with an empty cover image. This is because the cover can't be removed in `publikator-frontend`.
This simple workaround should prevent this going forward. Even if we add cover removing to `publikator-frontend` IMO this will still be good to have in place for production errors where it was forgotten to remove.
Make sure to bump styleguide in the backends afterwards:
- https://github.com/orbiting/backends/blob/master/packages/documents/package.json
- https://github.com/orbiting/backends/blob/master/servers/republik/package.json
and deploy `republik-publikator-api` (`republik-api` is not strictly necessary since preview mail, afaik, do have a cover).
> fix(Templates): prevent prominent error in newsletters without cover

- src/components/Dossier/Lead.js
- src/components/Figure/Byline.js
- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Image.md
- src/components/TeaserFront/Lead.js
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Split.md
- src/components/TeaserFront/Subject.js
- src/components/TeaserFront/Text.js
- src/components/TeaserFront/TileHeadline.js
- src/components/TeaserFront/index.js
- src/components/Typography/Editorial.js
- src/components/Typography/docs.md
- src/components/Typography/styles.js
- src/templates/Article/teasers.js
- src/templates/Article/utils.js
- src/templates/Format/index.js
- src/templates/Front/docs.md
- src/templates/Front/index.js
Main changes:
- optional `subject` element in front of lead
- a `framed` variant of FrontImage (container margin and switch to black headline in stacked mode)
- a `framed` variant of FrontSplit (basically the existing non-portrait teaser with adjusted margins)
- FrontTile updates for three tiles in a row: smaller headline and subject/lead font sizes
FYI, Luki's request for this was having the `subject` (better names welcome) as a block-level element on the markdown level in Publikator. That's why subject + lead have turned into inline elements. Open for better suggestions.
- Will use H3 on the markdown level (placed between title and lead)
- It's optional and shall be used in Feuilleton teasers only
- All front teaser leads will use 22px on desktop now
- Subject and lead are inline …
> Feuilleton front

- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/docs.md
This hit us again when introducing the autoPlay flag on Publikator, which doesn't autoplay the video on iOS only. I'd vote for adding the cross-platform magic here.
> feat(VideoPlayer): isCinemagraph flag

- src/components/Logo/index.js
Useful to support different logos on `.love`:
> feat(Logo): expose ratio

- src/components/TeaserFront/CreditLink.js
- src/templates/Front/index.js
> fix(CreditLink): support collapsedColor (similar to Subject)

- src/components/Figure/Byline.js
- src/components/TeaserFront/Format.js
- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Image.md
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Split.md
- src/components/TeaserFront/index.js
- src/templates/Front/index.js
Design requires the format on feuilleton teasers to be gray (analogue to the Subject component). Currently the format on front teasers just inherits the container color.
Significant changes:
- Rename `framed` flag to `feuilleton` (so we have one combined flag to trigger any feuilleton-specific styles)
- Add `feuilleton` checkbox to FrontTile and FrontTypo teasers as well
- If the teaser is `feuilleton`, mix the color (analogue to the Subject component), otherwise inherit as before.
> feat(TeaserFront): mix format color for `feuilleton` teasers

- src/components/TeaserFront/TileHeadline.js
- src/templates/Front/index.js
- Enables titleSize dropdown for FrontTile
- Renames existing `mediumSize` style to `standardSize` to avoid confusion
- Support `mediumSize` (a bit larger than standard) for col2 titles, as required for feuilleton.
> feat(TileHeadline): support 'medium' size (used for feuilleton)

- src/components/Typography/Editorial.js
- src/templates/Article/docs.md
- src/templates/Article/index.js
- src/templates/Front/docs.md
- src/templates/Front/index.js
> feat(Article): support Subject in article titleblock

- src/templates/Article/index.js
This is actually a Publikator fix to reflect the default format colors in the preview teaser.  (The teaser itself needs some work to actually show something more meaningful than it currently does, but for now the only goal is to make colors visible.)
> fix(Format): reflect format color in Publikator teaser

- src/components/Format/Tag.js
- src/components/Format/docs.md
- src/components/Format/index.js
- src/index.js
- src/lib.js
- src/templates/Article/index.js
- src/templates/Format/index.js
Docs: https://r-styleguide-pr-166.herokuapp.com/format
Moves the component over from https://github.com/orbiting/republik-frontend/pull/176 so it can be re-used both on 
- republik-frontend (Rubriken page) and 
- publikator-frontend (format teaser preview)
> feat(FormatTag): move format tag to styleguide

- src/components/TeaserFront/Image.js
- src/components/TeaserFront/Split.js
- src/components/TeaserFront/Text.js
Only affects FrontImageTeaser and FrontSplit (FrontTypo and FrontTile are always centered).
> fix(Front): enforce centered text for mobile feuilleton teasers

- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/docs.md
- src/components/VideoPlayer/fullscreen.js
- src/templates/Article/docs.md
- src/templates/Article/index.js
Changes
- add new full window mode and make it the default fallback when fullscreen API is not available
- ensure the first found fullscreen api (newest) is used and not the last supported on (oldest)
- allow to inject props to video players in a template via `getVideoPlayerProps`
> VideoPlayer: Full Window Mode

- src/components/Form/Radio.js
- src/components/Form/docs.md
Without a label, an inactive radio button is indistinguishable from a disabled one. A black border adds visibility to the `Radio` component and aligns its design with the `Checkbox` component.
Alternatively, a `black` prop could be added to the component to make it black and white (like on the `Button` component).
> Improve visibility of inactive radio button

- src/templates/Article/teasers.js
Several people here agreed we should 
- not show a generic message that basically says "Here's something you don't get" 
- rather only show a meaningful message if defined in Publikator
> fix(articleCollection): don't show generic unauthorized message 

- src/components/Comment/Comment.js
- src/components/Comment/CommentActions.js
- src/components/Comment/docs.md
- src/components/CommentTree/Row.js
- src/components/CommentTree/comments.js
- src/lib/translations.json
- src/templates/Discussion/index.js
Related to
https://github.com/orbiting/republik-frontend/pull/200
https://github.com/orbiting/backends/pull/118
- add optional "collapsable" UI 
- explicit upvotes/downvotes instead of single score
- share icon in actions bar
- A discussion can be flagged as `collapsable` in Publikator
- If a discussion is collapsable, the comment component measures whether its body is significantly higher than the max height and therefore `shouldCollapse`, and reports that back to the HOC row
- the row passes `collapsed` prop down to `Comment` and `CommentActions` (note that `true/false` triggers the respective UI while `undefined` triggers nothing)
https://r-styleguide-pr-181.herokuapp.com/components/comment#ltcommentactions-gt
> feat(Comment): misc improvements (collapsing, upvotes/downvotes, share)

- src/components/Chart/Bars.docs.md
- src/components/Chart/Bars.js
- src/components/Chart/index.js
- src/components/Chart/utils.js
Add inline text support for nice voting and election bars. [Docs](https://r-styleguide-pr-185.herokuapp.com/charts/bars#inline-values-and-labels).
Even with links for candidate profiles:
> Bars with Inline Text

- src/components/Comment/CommentActions.js
Minor UI fix which makes collapsed and expanded state better distinguishable without reading the label. (Think: There's a line, so it can be expanded.) Suggested by users.
> fix(CommentActions): hairline only if comment is collapsed

- src/components/Typography/index.js
- src/templates/Article/index.js
- src/templates/Article/utils.js
I've disabled underlines for sub/sups for now. Here's how they would look like with a regular link underline:
Ideally, a sup nested inside linked text shouldn't interrupt the main underline.
> fix(Article): support sub/sup in link, strong and emphasis

- src/components/Form/Autocomplete.js
- src/components/Form/docs.md
`icon` is already supported on `Input`, just piping it through (needed for new dialog page).
Docs preview: https://r-styleguide-pr-194.herokuapp.com/forms#autocomplete
> feat(Autocomplete): support icon and autocomplete props

- src/templates/Article/docs.md
- src/templates/Article/teasers.js
Fixes https://github.com/orbiting/publikator-frontend/issues/181
The front's `subject` rule relies on the number of `columns` stored in the teasergroup data. Since we don't store `columns` data for articleCollections, we hardcode `columns: 3` here to trigger the correct font-size.
> fix(articleCollection): trigger correct subject font-size for 3-column layout

- src/components/TeaserFront/Subject.js
- src/templates/Article/teasers.js
Prerequisite for https://github.com/orbiting/publikator-frontend/pull/185
- sets `formatColor` on subject from teaser data
- enables `formatColor` color picker on editor
- remove `collapsedColor` which is irrelevant for article collection tiles
> fix(articleCollection): support formatColor 

- src/components/Dossier/Lead.js
- src/components/List/List.js
- src/components/TeaserFeed/Lead.js
- src/components/Typography/Editorial.js
- src/components/Typography/docs.md
- src/components/Typography/styles.js
Also updating 
- closely related elements (Editorial.UL, Editorial.OL, Editorial.Question)
- similar `16/19` font-size pairs (TeaserFeed.Lead)
- other 16px mobile serif fonts (TeaserFrontDossierLead)
I didn't touch InfoBox which still looks good to me (slightly losing visual weight on mobile compared to normal text), but open for suggestions here. FYI, InfoBox title is (still) 16px, InfoBox text is (still) 15px.
FYI, existing `serifRegular17` with higher line-height only used on List, so no side effects expected from there: https://github.com/search?q=org%3Aorbiting+serifRegular17&type=Code
> fix(Editorial): bump up mobile font-size from 16px to 17px

- src/templates/Article/index.js
- src/templates/Discussion/index.js
Depends on https://github.com/orbiting/backends/pull/159
This will allow to close (and re-open) a discussion via the Publikator UI. If template is `article`, the auto-discussion will be closed. If template is `discussion`, the classic discussion will be closed.
republik-frontend is ready to handle dialog box and linkedDiscussion icon appropriately:
https://github.com/orbiting/republik-frontend/commit/d7c8a293bf39b8c158f2e2853450679a2bcd5373
> feat: add discussionClosed flag to article and discussion template

- src/components/CommentTeaser/CommentTeaser.js
- src/index.js
- src/lib.js
- src/lib/inQuotes.docs.md
- src/lib/inQuotes.js
Utility function for wrapping a string in quotation marks and avoiding double quoting. Ignores already quoted strings of the same quotation marks pattern and replaces nested quotation marks.
Docs: https://r-styleguide-pr-203.herokuapp.com/dev/inQuotes
> feat(inQuotes)

- src/components/Typography/docs.md
- src/components/Typography/index.js
Preview in context: https://r-styleguide-pr-204.herokuapp.com/typography#sub-and-super-script
> fix(subSup): avoid illegible multi-line mess while preserving no underline in link

- .gitignore
- package.json
- src/chart.js
- src/components/Chart/Bars.docs.md
- src/components/Chart/Bars.js
- src/components/Chart/Lines.docs.md
- src/components/Chart/Lines.js
- src/components/Chart/Lines.layout.js
- src/components/Chart/Lollipops.docs.md
- src/components/Chart/ScatterPlots.docs.md
- src/components/Chart/ScatterPlots.js
- src/components/Chart/Slopes.docs.md
- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBars.js
- src/components/Chart/index.js
- src/components/Chart/utils.js
- src/components/DynamicComponent/docs.md
- src/components/DynamicComponent/index.js
- src/lib/timeFormat.js
- src/lib/translations.json
Refactoring
- remove `t` dependency from charts, only use `tLabel` (an transform function that could translate)
Fix
- use de ch time format
Feat
- expose chart via dedicated end point
- allow to use in dynamic component
> Chart Entry Point

- src/templates/Article/index.js
Allows to tag existing articles ahead of launching the reading list. We will infer the audio icon from audioSrc… meta field(s) until there's a use case for a manual flag.
> feat(Article): add Publikator flags to indicate video/gallery and disable text progress

- src/components/Form/Field.js
- src/components/Form/docs.md
- remove no longer used `isFocused` prop https://github.com/orbiting/styleguide/issues/174
- fix label overlap with `0` value
- clean up docs a bit
> Field Cleanup

- .github/main.workflow
github workflow to build and upload pack to S3.
This allows you to use styleguide branches in other repos: 
```
"dependencies": {
"@project-r/styleguide": "https://s3.eu-central-1.amazonaws.com/republik-assets-dev/npm/project-r-styleguide-${BRANCH}.tgz"
}
```
> publish to S3

- src/components/AudioPlayer/Player.js
- src/components/AudioPlayer/docs.md
- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/docs.md
Removes the unused `startSeconds` prop and loads startSeconds via promise provided by frontend context.
> fix(MediaPlayers): load user progress from promise and remove unused startSeconds prop

- src/components/AudioPlayer/Player.js
- src/components/AudioPlayer/docs.md
- src/components/AudioPlayer/globalState.js
- src/components/VideoPlayer/Player.js
- src/components/VideoPlayer/docs.md
- src/components/VideoPlayer/fullscreen.js
- src/lib/warn.js
- src/templates/Article/index.js
_Update Thomas_
Focus on `AudioPlayer`. Also see updated docs. 
Additional Changes
- share global play state between audio and video player (prevent them playing on top of each other)
- `f` key for full screen in video player
- progress props on all center children and root elements except cover & title block
> fix(AudioPlayer): tentative fix for autoplay issues

- src/components/Button/docs.md
- src/components/Button/index.js
- src/components/Figure/docs.md
- src/components/Figure/index.js
- src/global.css
- src/index.js
- src/lib.js
- src/templates/Article/index.js
changes
- support audio cover via document meta data
- export plain button css rule
> Audio Cover

- src/components/Chart/ScatterPlots.docs.md
- src/components/Chart/ScatterPlots.js
> feat(ScatterPlots): custom axis labels and padding

- package-lock.json
- package.json
- src/components/CommentComposer/CommentComposer.js
Using [scroll-into-view](https://github.com/KoryNunn/scroll-into-view). The native `Element.scrollIntoView()` didn't work well because it does not support setting an offset, so the comment composer would scroll to the very top and be hidden behind the header.
Fixes https://github.com/orbiting/republik-frontend/issues/301
> Scroll the <CommentComposer> into view upon mount

- src/components/Collapsable/Collapsable.js
- src/components/Collapsable/docs.md
- src/components/Collapsable/index.js
- src/components/Discussion/Internal/Comment/Body.js
- src/components/Discussion/config.js
- src/components/InfoBox/InfoBox.js
- src/components/InfoBox/docs.md
- src/index.js
- src/lib/translations.json
- src/templates/Article/docs.md
- src/templates/Article/index.js
Implements collapsable infoboxes https://github.com/orbiting/styleguide/issues/228 and factors the collapsable logic out of `Comment/Body.js` into a shared `Collapsable` component.
Docs:
https://r-styleguide-pr-244.herokuapp.com/collapsable (new)
https://r-styleguide-pr-244.herokuapp.com/infobox#collapsable (new)
https://r-styleguide-pr-244.herokuapp.com/components/discussion/internal#body (unchanged)
TODO:
> feat(Infobox): collapsable

- src/components/Collapsable/Collapsable.js
- src/components/Collapsable/docs.md
- src/components/Form/Slider.js
- src/components/Typography/Editorial.js
- src/lib.js
– Increase slider thumb clickable surface
– Set editorial paragraph margins in rem
– Add alwaysCollapsed option to Collapsable component
> Slider fixes

- src/components/Button/docs.md
- src/components/Button/index.js
- src/components/Form/Checkbox.js
- src/components/Form/Field.js
- src/components/Form/docs.md
- src/components/RawHtml/docs.md
- src/components/RawHtml/index.js
- src/components/TitleBlock/docs.md
- src/components/TitleBlock/index.js
- src/components/Typography/index.js
- src/lib.js
- src/templates/Article/docs.md
- src/templates/Article/index.js
- src/templates/Format/index.js
- src/theme/colors.docs.js
- src/theme/colors.js
- include optional titleMargin option in the schema creator for both Article and Format schemas.
- remove unused TitleBlockAppend option from Article and Format schemas
- migrate negative colors to the styleguide
- add black option for checkbox
- add black option for raw html (for links)
- implement error styles for various elements in black mode
> Paynote v2

- src/components/Overlay/Overlay.js
This make the overlay server renderable without client server diff and still immediately using a portal if client rendered. Server rendered overlays will also end up using a portal after rehydration. To detect rehydration rendering and not immediately switch to portal rendering when dom is available—which would lead to a diff—a `data-overlay-ssr` attribute is set during ssr rendering and detected on the client.
> fix(Overlay): support SSR, refactor to hooks

- src/components/Chart/Bars.docs.md
- src/components/Chart/Bars.js
better inline label position for negative numbers and support for `inlineLabelPosition`
> feat(Bars): Advanced Labeling

- src/components/Dossier/Subheader.js
- src/components/TeaserFront/CreditLink.js
- src/components/TeaserFront/Tile.js
- src/components/TeaserFront/TileRow.js
- src/templates/Article/teasers.js
- handle default color scheme for teaser/tiles (based on color context)
**Needs to be tested for teasers with user set colors**
> Dark mode for related articles

- src/catalogTheme.css
- src/components/Chart/Bars.js
- src/components/Chart/Hemicycle.docs.md
- src/components/Chart/Hemicycle.js
- src/components/Chart/Lines.docs.md
- src/components/Chart/Lines.js
- src/components/Chart/Lines.layout.js
- src/components/Chart/Lollipops.docs.md
- src/components/Chart/Maps.js
- src/components/Chart/Maps.layout.js
- src/components/Chart/ScatterPlots.js
- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBars.js
- src/components/Chart/colorMaps.js
- src/components/Chart/docs.js
- src/components/Chart/index.js
- src/components/Colors/useColorContext.js
- src/components/TeaserFront/TileRow.js
Changes
- global color map support
- linear x axis for line chart
- lollipop improvements: alignment & `showBarValues` compat
- no auto `xTicks` with `showBarValues`
> Chart Improvements

- src/components/Callout/index.js
- src/theme/zIndex.js
Like the refactoring but the footer has a z-index of 11, which means the callout menu can potentially get hidden below it, which I believe should never happen.
> fix(Callout): place callout above footer

- src/templates/EditorialNewsletter/email/Center.js
This Pull Request changes `EditorNewsletter` footer part. It adds a delivery reason note and offers some advice on how to change newsletter settings.
Wording is ought to hinder misconstrued notions that unsubscribing from newsletters cancels (paid) subscription, and a newsletter is the actual product.
Wording ok'd with Community Plus gents, tested with internal and external NL recipients.
**After**
**Before**
> fix(EditorialNewsletter): Add delivery reason note to email/Center (footer)

- src/components/InfoBox/InfoBox.js
Reduces the Infobox size when collapsed. Approved by CR and Produktion.
new desktop:
new mobile:
previous desktop:
previous mobile:
> fix(Infobox): smaller size when collapsed

- src/templates/EditorialNewsletter/email/Button.js
With previous variant mailchimp wouldn't like it and autoformat would kick in and remove the border on secondary buttons.
> fix(EmailButton): change styling of email secondary button

- src/templates/EditorialNewsletter/docs.md
- src/templates/EditorialNewsletter/email/Center.js
When not member or active trial:
```
*|INTERESTED:Customer:Member,Geteilter Zugriff|* *|ELSE:|*
```
We display a teaser to start a trial. With special tokens (if not available it still works gracefully with an extra email verification step)
> feat(EditorialNewsletter): trial campaign for covid-19

- src/components/Chart/Bars.js
- src/components/Chart/Lollipops.docs.md
- src/components/Discussion/DiscussionContext.docs.js
- src/components/Discussion/Internal/Comment/Actions.js
- src/components/Discussion/Internal/docs.imports.js
- src/components/Discussion/Internal/docs.md
- src/components/TeaserActiveDebates/ActiveDebates.js
- src/index.js
- src/lib.js
- src/lib/translations.json
- src/templates/Front/liveTeasers.js
left: regular, middle: admin actions (black star), right: featured (green star)
Under the hood changes:
- new `TeaserActiveDebates` query with featured via API, depends on https://github.com/orbiting/backends/pull/418
- move flag icon after share icon (less accidental reply clicks)
> Featured Comments

- src/templates/EditorialNewsletter/email/Center.js
- src/templates/EditorialNewsletter/email/Header.js
> fix(EditorialNewsletter): Replace call to action w/ prominent link to trial

- src/components/Typography/Editorial.js
_It's black, it's white
It's tough for you to get by
It's black, it's white, woo_
This Pull Request uses color context in `Typography/Editorial/Note` to render notes in dark mode as well.
> fix(Typography): Provide color context to Editorial.Note

- src/components/Callout/index.js
- src/components/Typography/Editorial.js
- src/components/Typography/Interaction.js
- src/components/Typography/Meta.js
- src/components/Typography/docs.md
- src/components/Typography/index.js
- src/components/Typography/styles.js
- src/lib.js
- src/lib/useBodyScrollLock.js
- src/templates/Article/base.js
- src/templates/Article/blocks.js
- src/templates/Article/docs.md
- src/templates/Article/index.js
- src/templates/Article/utils.js
- src/templates/Format/docs.md
- src/templates/Format/index.js
- src/templates/Section/docs.md
- src/templates/Section/index.js
Changes
- new `Meta` typography, with same spacing and font sizes as `Editorial`
- bump `Interaction.P`
- refactor article templates code: split into multiple files
- `metaBody` for `section` and `format` template
- `data-body-scroll-lock-ignore` attribute for horizontal scrollers in body locks
- rm box shadow from call outs (felt like a visual bug)
- small code clean ups
> Sections with Meta Body & Cleanup

- src/components/IconButton/index.js
Right before the release of the action bar, I changed the IconButton default margin from 20px to 18px. I think it's a bit too narrow and on small mobile phones users could benefit from a bit more space, so I reverted it back to 20px. See narrowest scenario below iPhone 5S (it's subtle): 
after:
before
> Increase margin on IconButton

- src/components/InfoBox/InfoBox.js
- src/components/LazyLoad/Image.js
- src/components/LazyLoad/docs.md
- src/components/LazyLoad/index.js
- src/components/TeaserCarousel/Carousel.js
- src/components/TeaserMyMagazine/TeaserMyMagazine.js
- src/components/TeaserShared/SectionTitle.js
- src/templates/Front/liveTeasers.js
- `editorPreview` for `TeaserMyMagazine` when there is no content
- fix `SectionTitle` color, revert to using inherit instead of react context (was causing wrong coloured title above carousels, see screenshot)
- refactor `LazyLoad`, ensure no placeholder wrapper is left over after everything is ready
- refactor `editorPreview` naming in InfoBox
> Fine Tune TeaserMyMagazine

- src/components/Colors/useColorContext.js
- src/components/TeaserFeed/index.js
- src/components/TeaserMyMagazine/TeaserMyMagazine.js
- src/theme/colors.js
Monkey patch color values in teaser feed elements in a dark context:
becomes bright:
> Fix format color in dark context

- src/chart.js
- src/components/Chart/Bars.docs.md
- src/components/Chart/Bars.js
- src/components/Chart/ColorLegend.js
- src/components/Chart/Hemicycle.docs.md
- src/components/Chart/Hemicycle.js
- src/components/Chart/Lines.docs.md
- src/components/Chart/Lines.js
- src/components/Chart/Lines.layout.js
- src/components/Chart/Lollipops.docs.md
- src/components/Chart/Maps.docs.md
- src/components/Chart/Maps.js
- src/components/Chart/ScatterPlots.docs.md
- src/components/Chart/ScatterPlots.js
- src/components/Chart/Slopes.docs.md
- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBars.js
- src/components/Chart/index.js
- src/index.js
- src/templates/Article/index.js
Changes
- lines: remove y connector lines
- lines:use y connector circles when necessary (more than one label has been moved from the center of the line)
- lines: support `"endValue": false`. Should only be done when the value is truly irrelevant.
- all: up color legend before chart, except for hemicycle where the color legend only contains values that are below the display threshold
- bars: move x axis label on top too
- all: clean up
> Color Labels

- src/components/TeaserFront/Image.js
- src/components/TeaserMyMagazine/TeaserMyMagazine.js
- src/components/TeaserMyMagazine/__docs__/myMagazineExamples.js
- src/components/TeaserMyMagazine/docs.md
- src/templates/Article/base.js
- src/templates/Article/blocks.js
- Light Layout, dezente graue Borders bei Weiterlesen ala «Durch die Woche» Karussell
Done, ausser "dezente graue Borders". Die wirken meines Erachtens nicht gut und beissen sich mit den Borders im User Nav. Würde eine allgemeinere Revision begrüssen, statt jetzt Inkonsistent einzuführen.
todo:
- [ ] apply lastDays filter
preview:
> MyMagazine Revision

- src/theme/colors.js
Reverts the secondary color to previous version. Replacing everything with textSoft is too risky IMO and could lead to unwanted consequences. We need to look at individual usecases in components and look at "why is it necessary that it's secondary" and then choose either text, textSoft, primary or disabled for each case.
> fix(colors): revert secondary

- src/components/Social/Tweet.js
- src/components/Social/docs.md
> fix(Tweet): wordwrap

- src/components/Chart/Bars.docs.md
- src/components/Chart/ColorLegend.js
- src/components/Chart/Hemicycle.js
- src/components/Chart/Lines.js
- src/components/Chart/Maps.js
- src/components/Chart/ScatterPlots.js
- src/components/Chart/TimeBars.js
- src/components/Chart/index.js
- src/components/Colors/ColorContext.js
- src/components/Colors/docs.md
- src/components/Colors/useColorContext.js
- src/components/Discussion/Internal/Comment/CommentCountIcon.js
- src/components/Dossier/Subheader.js
- src/components/Figure/Caption.js
- src/components/IconButton/index.js
- src/components/Social/Tweet.js
- src/components/Social/docs.md
- src/components/TeaserCarousel/Format.js
- src/components/TeaserCarousel/docs.md
- src/components/TeaserFront/CreditLink.js
- src/components/TeaserFront/TileRow.js
- src/components/TeaserMyMagazine/TeaserMyMagazine.js
- src/index.js
- src/lib.js
- src/theme/colors.js
- feat(colors): ColorContextLocalExtension
- feat(Charts): custom dark mode colors via colorDarkMapping
- fix(Charts): add missing color mappings for dark mode
- refactor(colors): clean naming, always use `set` or `getCSSColor`
`ColorContextLocalExtension` allows to define new variables for a specific local react tree.
Based on that support for `colorDarkMapping` in chart configs was added. Allowing to re-map certain bright colors to dark colors when in dark mode. Not sure about naming yet. 
Also `colorScheme.text` et al are no longer available.
> Dark Mode Round 99

- src/components/IconButton/index.js
see https://caniuse.com/css-initial-value
I don't see any benefit of using initial here but maybe I'm overseeing something.
> fix(IconButton): display labels in IE11

- package.json
- src/components/CommentTeaser/CommentTeaser.js
- src/components/Discussion/Internal/Comment/Actions.js
- src/components/Discussion/Internal/Comment/Body.js
- src/components/Discussion/Internal/Comment/Header.js
- src/components/Discussion/Internal/docs.md
- src/lib/translations.json
Comments can be unpublished. Header will replace author with a label.
If comment was unpublished by admin (`adminUnpublished`), label will indicate that.
> Discussion: Hide unpublished nodes

- src/components/TeaserActiveDebates/ActiveDebates.js
If a comment is unpublished, the author can still query `Comment.preview`.
Thus far, `TeaserActiveDebates` would have rendered that comment for said author despite being unpublished (and not visible to others).
This Pull Request intends to fix that.
> fix(TeaserActiveDebates): Filter unpublished comments

- src/components/Discussion/Internal/Comment/Actions.js
- src/components/Icons/CustomIcons/ShareIconIOS.js
> fix(Discussion): consistent share icon (and position swap)

- src/components/AudioPlayer/Player.js
- src/lib/translations.json
This pull request is a first shot at addressing issue #312.
I added forward and backward buttons to the player that skip forward/backward 30 seconds in the audio file when clicked. 
10 or 5 seconds would be the alternative to skipping 30 seconds as these icons are also available in the Material Iconset.
This is how the new buttons look (screenshot taken from the styleguide):
Some remaining questions from my side:
Should we make the button display optional? (as with the download button)
And the mobile view seems a bit crowded with buttons now: should we display them on mobile?
Would love to hear your thoughts about my first PR in one of the orbiting Repos.
> add rewind & skip buttons

- src/components/Chart/Bars.js
Two steps:
1. calculate everything needed to render the `segments` based on their original order (the `map`part of `precalculatedData`)
2. if an `inlineLabel` is present, sort the `segments` so that the ones with a label get rendered last (`sort` part)
> fix(BarChart): render bars with labels last

- src/components/CommentTeaser/CommentTeaser.js
- src/components/CommentTeaser/docs.md
- src/components/Discussion/DiscussionContext.docs.js
- src/components/Discussion/Internal/Comment/Actions.js
- src/components/Discussion/Internal/Comment/Header.js
- src/components/Discussion/Internal/Comment/RelativeTime.js
- src/components/Discussion/Internal/docs.md
- src/components/TeaserActiveDebates/DebateTeaser.js
- src/lib.js
- src/lib/translations.json
- src/lib/useCurrentMinute.js
Move `now` out of discussion context and instead into an `useCurrentMinute` hook. The new hook is then directly used around the DOM element that relies on the current time. This greatly reduced the React conciliation effort necessary.
Before it took at least 40ms, often 60 to 90ms on an M1 with Chrome:
Afterwards we're down to 20ms:
Even tested in IE11 and eliminates the worst freezes. Generally I'd expect this to have a greater positiv impact on slower devices.
> Current Minute

- src/components/ShareImage/ShareImagePreview.js
The default text of ShareTafeln is actually the Republik Font (serifTitle) and not the GT America (serifBold). See example from sketch file: 
GT America is never used in ShareImages, which lucky for us means we can just swap the two fonts.
Sketch file for reference:
https://drive.google.com/file/d/1ywqwE-We-izYf1psxtvll1q4fuw5gi3d/view?usp=sharing
> fix(ShareImage): swap editorial default font

- src/components/ShareImage/ShareImagePreview.js
- src/components/ShareImage/SharePreviewTwitter.js
fixes bug that katrin pointed out: Because a border of 2px was applied to the twitter preview and not the facebook preview (in publikator), the two would break words at different sizes:
new result with box-shadow, which doesn't take up space like borders do:
> fix(ShareImage): replace border with boxShadow on Twitter

- src/components/ShareImage/ShareImagePreview.js
There was no line-height specified on the div containing the share image text. For ShareImages with GT-America, this lead to the scrollHeight sometimes to being higher than the clientHeight. It would also cut off the lower parts of the text:
before:
by setting a proper line-height (html defaults to 1.15, which is not enough for gt america):
> fix(ShareImage): add missing line-height

- src/components/SeriesNav/SeriesNav.js
- src/components/SeriesNav/SeriesNavTile.js
- src/components/SeriesNav/SeriesNavTileContent.js
- src/components/SeriesNav/__docs__/seriesNavExample.js
- src/components/SeriesNav/docs.md
- src/lib/translations.json
- src/templates/Article/teasers.js
- remove inverted current episode style and replace with medium label (leaves paynote as is for now)
before:
after:
before:
after:
before:
after:
- adds link to overview to inline description
- adds minWidth to tiles 
before
after
> Series Nav fixes

- src/components/Chart/Bars.js
- src/components/Chart/Lines.js
- src/components/Chart/ScatterPlotGroup.js
- src/components/Chart/ScatterPlots.js
- src/components/Chart/TimeBarGroup.js
- src/components/Chart/XAxis.js
- src/components/Chart/docs.js
- src/components/Chart/index.js
Small changes for smooth SVG export:
- allow to disable canvas rendering from the outside
- mark axis groups for easy removal
- we used to remove all line elements but annotation lines should actually not be removed
> Fix Svg Export

- src/components/Discussion/Composer/CommentComposer.js
- src/components/Discussion/Composer/docs.imports.js
- src/components/Discussion/DiscussionContext.docs.js
- src/components/Discussion/Internal/Composer/Actions.js
- src/lib.js
- src/lib/translations.json
based on https://github.com/orbiting/styleguide/pull/410
Sample predicate function – to find unescaped asteriks – is a bit more subtle now.
Curiosity led then to improve over label approach. Raising that to an array of hints. A series of predicate functions can run while typing and return one ore more hints.
Went down that rabbithole because there are several other hints we might add e.g. if text contains nothing but a link, show a hint: Posting links are best with some context.
> feat(CommentComposer): Show hints while typing

- src/components/SeriesNav/SeriesNav.js
- src/lib/translations.json
Wrap Link in another translation string to allow a trailing period.
> fix(SeriesNav): Use Link w/ label as placeholder in parent translation

- src/components/Chart/Bars.js
- src/components/Chart/TimeBarGroup.js
- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBars.js
- src/components/Chart/XAxis.js
- src/components/Chart/utils.js
Add the option to add an xUnit to a Time Bar. In the config file, one can add an xUnit and then the unit will rendered at the last available bar.
> Add xUnit to Time Bar Chart

- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBarsAnnotations.js
Add options for some text alignment and text labels on the left side
- Using two points (x1 and x2) the boolean leftLabel removes the x1 circle and draws a line from the YAxis to the x2 point
- The text alignment of X annotations can be modified by using textAlignment with the options left, right and center, if undefined it defaults to the previous system.
> fix(leftLabel): add boolean to align annotations on left side

- src/components/Chart/TimeBars.docs.md
- src/components/Chart/TimeBarsAnnotations.js
An error in the markdown and if else for leftLabel was false.
Time bars is currently not loading correctly, in time bars it should look like this instead:
> fix(leftLabel): get the if else clauses right

- src/components/BlockQuote/BlockQuoteParagraph.js
The color of the blockquote-paragraph is now defined on the component level, so that the text-color is no longer based on the inherited style.
> fix(BlockQuoteParagraph): no longer rely on inherited text-color

- src/templates/EditorialNewsletter/email/Header.js
(uses assets provided in https://github.com/orbiting/republik-frontend/pull/635)
> fix(EditorialNewsletter): Use 3rd wave logo

- src/components/Figure/Caption.js
- src/components/Figure/Image.js
- src/components/Figure/docs.md
- src/components/Figure/index.js
- src/lib.js
- src/templates/Article/base.js
- export gallery min width requirement 
- bring group caption up so they match with regular captions
_before_
_after_
Note: while it would have technically been possible to avoid using negative margins, this would require the more convoluted process of getting all the images in a group, checking which ones are in the last row and removing the bottom margin for those.
> Gallery fixes

- src/components/Chart/utils.js
Currently, if we use the chart components in a dynamic component, the value column of the data has to be a string. With this fix, we can also use number data without converting it to strings.
> fix(hasValues): convert numbers to string to evaluate length

- src/components/Discussion/Composer/CommentComposer.js
- src/components/Discussion/Composer/CommentDraftHelper.js
- src/components/Discussion/Tree/CommentList.js
This pull-request aims to solve an issue caused by a shared draft for all inputs on a discussion. Now each input is saved on it's own and can thus be saved without overlap.
https://user-images.githubusercontent.com/30313631/134655241-377cd854-73fc-47b2-a798-78800b9a08cc.mov
https://user-images.githubusercontent.com/30313631/134655493-5e14b998-908e-45f7-ac82-9ba6b660bc9d.mov
(at 6 seconds you see how previous drafts get migrated)
> Improve method to persist draft-values for input fields inside discussions

- src/components/ShareImage/ShareImagePreview.js
- src/components/ShareImage/SharePreviewFacebook.js
- src/components/ShareImage/SharePreviewTwitter.js
- src/components/ShareImage/docs.md
- src/components/TeaserEmbedComment/index.js
- src/index.js
- src/lib.js
The production team asked for an update of the social previews. With special attention to how much text is realistically shown.
Twitter and Facebook are quite responsive nowadays so it's hard to settle on a width. The width I've used are from post feeds on my laptop with 1440x. Mobile usually skips the description on both services.
Also updated fonts and other styles.
> Improve Social Preview

- src/components/TeaserEmbedComment/index.js
- src/templates/Article/index.js
> fix(TeaserEmbedComment): remove whitespace for multiple embeds in a row

- src/components/Figure/Image.js
- src/components/SeriesNav/SeriesNavTile.js
This change is required to hide the PayNote for members when showing statically generated sites, before React has rehydrated the page.
> fix(SeriesNav): hide paynote if a user has an active membership

- src/components/Discussion/Composer/CommentComposer.js
Bug: the tag radio buttons in composer revert to the active tag when user starts typing.
Now the selection stays put.
> Fix comment composer bug

- src/components/Tabs/Scroller.tsx
- src/components/Tabs/docs.md
Only animate in effect when `activeChildIndex` is changing.
> fix(Tabs): only scroll into view when not initial mount

- src/components/Tabs/TabButton.tsx
The borderColor: 'trasparent' was overwriting the bordercolor applied to the tabitem component
This fixes the issue:
before:
after:
> fix(TabButton): fix borderColor bug in TabButton

- src/lib/slug.js
- src/lib/slug.test.js
**Context:** in Publikator, we watch the document title and adjust the slug accordingly. Having a `&shy;` entity be interpreted as a `-` in the slug is confusing behaviour. We now filter them out.
_Tested_ with Publikator
> Improve slug
